### ISSUE TITLE
mount: '/system' not in /proc/mounts

### ISSUE THREAD

**Issue by BoostUpStation** [ballerburg9005/android-exfat-ntfs-ext4-sdcard-usb-otg-mount-hack#1]
Hi, getting an error while remounting the system via adb.
Doogee V Max with 512GB ext4 sdcard and journal enabled by default.
Bootloader unlocked, rooted with magisk, android 12, kernel version is 4.19.191

M23H:/ # mount -o rw,remount /system
mount: '/system' not in /proc/mounts

When trying with this command, still errors :-
$ adb shell
M23H:/ $ su
M23H:/ # mount -o rw,remount /
M23H:/ # cp /sdcard/binaries/bin/* /system/bin/
cp: /system/bin//fsck.exfat: Read-only file system
cp: /system/bin//fsck.ntfs: Read-only file system
cp: /system/bin//mkfs.exfat: Read-only file system
cp: /system/bin//mkfs.ntfs: Read-only file system
cp: /system/bin//mount.exfat: Read-only file system
cp: /system/bin//mount.ntfs: Read-only file system
cp: /system/bin//mountsd: Read-only file system

Please tell how to resolve this.

**Comment by ballerburg9005** [comment]
I would have to see the output of "mount", maybe your phone has /system/bin as an individual mount point.

**Comment by BoostUpStation** [comment]
![mount.txt](https://github.com/ballerburg9005/android-exfat-ntfs-ext4-sdcard-usb-otg-mount-hack/files/13309185/mount.txt)

Attached here is the file, please have a look at it.
thank you.

**Comment by BoostUpStation** [comment]
Yeah, right.
/system/bin is an individual mount.
so instead of using: 
mount -o rw,remount /system
mount -o ro,remount /system

FIX
had to use:
mount -o rw,remount /system/bin
mount -o ro,remount /system/bin
